vim.api.nvim_set_keymap('n', '<c-s>', ':w<CR>', {})
vim.api.nvim_set_keymap('i', '<c-s>', '<Esc>:w<CR>a', {})
vim.api.nvim_set_keymap('n', '<c-j>', '<c-w>j', { noremap=true })
vim.api.nvim_set_keymap('n', '<c-k>', '<c-w>k', { noremap=true })
vim.api.nvim_set_keymap('n', '<c-h>', '<c-w>h', { noremap=true })
vim.api.nvim_set_keymap('n', '<c-l>', '<c-w>l', { noremap=true })
